### ISSUE TITLE
Shield  bonus and misc armor bonus not showing up

### ISSUE THREAD

**Issue by Mapes** [tomfoster70/dnd_python_parse#4]
Title says it all.   Although I'm multi classed so that might be confusing things.   This was on Windows with Python 2.7.13

**Comment by Mapes** [comment]
[Rundle_Rogue4Fighter6Wizard2w.txt](https://github.com/tomfoster70/dnd_python_parse/files/1560980/Rundle_Rogue4Fighter6Wizard2w.txt)

**Comment by tomfoster70** [comment]
I have fixed the armor class now, this should be done

**Comment by Mapes** [comment]
Verified fixed
