### ISSUE TITLE
Spells not being populated

### ISSUE THREAD

**Issue by Mapes** [tomfoster70/dnd_python_parse#5]
I'm multiclassed and I also include in the spell title components and whether concentration is required and my class that granted the spell  like  this
Protection Good/Evil VSMc W

**Comment by Mapes** [comment]
Hmm trying to attach the file but,  github wont let me

**Comment by Mapes** [comment]
I should mention it's on windows 10 with python 2.7.13

**Comment by Mapes** [comment]
[Rundle_Rogue4Fighter6Wizard2w.txt](https://github.com/tomfoster70/dnd_python_parse/files/1560979/Rundle_Rogue4Fighter6Wizard2w.txt)

**Comment by tomfoster70** [comment]
I have now hopefully fixed this bug and committed a fixed

**Comment by Mapes** [comment]
Verified fixed
